/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#4f17ce",
        "primary-container": "#673de6",
        "primary-fixed": "#e7deff",
        "primary-fixed-dim": "#ccbeff",
        "on-primary": "#ffffff",
        "on-primary-container": "#e1d7ff",
        "on-primary-fixed": "#1e0060",
        "on-primary-fixed-variant": "#4c10cc",
        secondary: "#545e79",
        "secondary-container": "#d5dfff",
        "secondary-fixed": "#d9e2ff",
        "secondary-fixed-dim": "#bcc6e5",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#58627d",
        "on-secondary-fixed": "#101b32",
        "on-secondary-fixed-variant": "#3c4660",
        tertiary: "#2b5140",
        "tertiary-container": "#436957",
        "tertiary-fixed": "#c2ecd5",
        "tertiary-fixed-dim": "#a7d0ba",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#bde7d0",
        "on-tertiary-fixed": "#002114",
        "on-tertiary-fixed-variant": "#294e3d",
        surface: "#faf9fb",
        "surface-dim": "#dbd9dc",
        "surface-bright": "#faf9fb",
        "surface-variant": "#e3e2e4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f5",
        "surface-container": "#efedf0",
        "surface-container-high": "#e9e8ea",
        "surface-container-highest": "#e3e2e4",
        "surface-tint": "#6439e3",
        "on-surface": "#1b1c1e",
        "on-surface-variant": "#484455",
        "on-background": "#1b1c1e",
        background: "#faf9fb",
        "inverse-surface": "#2f3032",
        "inverse-on-surface": "#f2f0f3",
        "inverse-primary": "#ccbeff",
        outline: "#797487",
        "outline-variant": "#cac3d8",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
