/** @type {import('tailwindcss').Config} */

// Helper: reference a CSS var in rgb(var(--name) / <alpha>) format
const v = (name) => `rgb(var(--color-${name}) / <alpha-value>)`;

export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: v("primary"),
        "primary-container": v("primary-container"),
        "primary-fixed": v("primary-fixed"),
        "primary-fixed-dim": v("primary-fixed-dim"),
        "on-primary": v("on-primary"),
        "on-primary-container": v("on-primary-container"),
        "on-primary-fixed": v("on-primary-fixed"),
        "on-primary-fixed-variant": v("on-primary-fixed-variant"),
        secondary: v("secondary"),
        "secondary-container": v("secondary-container"),
        "secondary-fixed": v("secondary-fixed"),
        "secondary-fixed-dim": v("secondary-fixed-dim"),
        "on-secondary": v("on-secondary"),
        "on-secondary-container": v("on-secondary-container"),
        "on-secondary-fixed": v("on-secondary-fixed"),
        "on-secondary-fixed-variant": v("on-secondary-fixed-variant"),
        tertiary: v("tertiary"),
        "tertiary-container": v("tertiary-container"),
        "tertiary-fixed": v("tertiary-fixed"),
        "tertiary-fixed-dim": v("tertiary-fixed-dim"),
        "on-tertiary": v("on-tertiary"),
        "on-tertiary-container": v("on-tertiary-container"),
        "on-tertiary-fixed": v("on-tertiary-fixed"),
        "on-tertiary-fixed-variant": v("on-tertiary-fixed-variant"),
        surface: v("surface"),
        "surface-dim": v("surface-dim"),
        "surface-bright": v("surface-bright"),
        "surface-variant": v("surface-variant"),
        "surface-container-lowest": v("surface-container-lowest"),
        "surface-container-low": v("surface-container-low"),
        "surface-container": v("surface-container"),
        "surface-container-high": v("surface-container-high"),
        "surface-container-highest": v("surface-container-highest"),
        "surface-tint": v("surface-tint"),
        "on-surface": v("on-surface"),
        "on-surface-variant": v("on-surface-variant"),
        "on-background": v("on-background"),
        background: v("background"),
        "inverse-surface": v("inverse-surface"),
        "inverse-on-surface": v("inverse-on-surface"),
        "inverse-primary": v("inverse-primary"),
        outline: v("outline"),
        "outline-variant": v("outline-variant"),
        error: v("error"),
        "error-container": v("error-container"),
        "on-error": v("on-error"),
        "on-error-container": v("on-error-container"),
      },
      fontFamily: {
        headline: ["Noto Serif", "serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
