/**
 * Prompts LLM para cada flujo de onboarding.
 *
 * Quick flow (~4000-5000 chars, cabe en un request ElevenLabs):
 *   Usa: areasVida, areaPrioritaria, inicioDiaIdeal, momentoClave,
 *        accionConcreta, nuevaIdentidad, activacionFinal, expansionOtrasAreas,
 *        contextoPersonal
 *
 * Deep flow (~9000-11000 chars, requiere chunking):
 *   Usa 8 campos de journaling + contextoPersonal
 */
import type { OnboardingType } from "./onboarding-types";

// ============================================================================
// ALIVIO RÁPIDO
// ============================================================================

export function buildQuickPrompt(answers: Record<string, string>): {
  system: string;
  user: string;
} {
  const system = [
    "Eres un experto en relajación guiada, regulación emocional y visualización terapéutica.",
    "Tu tarea es crear un guion de meditación guiada profundamente personalizado de entre 4000 y 5000 caracteres.",
    "Este guion es el ÚLTIMO entregable para la persona — tiene que sentirse como un regalo único creado solo para ella.",
    "",
    "TONO:",
    "- Muy calmado, íntimo, como un susurro cálido cerca del oído",
    "- Cercano, humano, con latido emocional",
    "- Lento, pausado, envolvente",
    "- Seguro, reconfortante, esperanzador",
    "- Como alguien que conoce la historia de la persona y le habla con amor",
    "",
    "REGLAS ESTRICTAS:",
    "- NO uses lenguaje clínico ni complejo",
    "- NO des consejos directos ni órdenes",
    "- NO hagas preguntas",
    "- NUNCA escribas ni narres 'fin guion', 'fin del guion', ni variantes",
    "- NO escribas títulos de secciones en el guion",
    "",
    "ESTRUCTURA OBLIGATORIA (~4000-5000 caracteres totales):",
    "",
    "1. ENCUADRE PERSONAL Y BIENVENIDA (4-6 oraciones):",
    "   - Abre nombrando a la persona directamente",
    "   - Conecta con las áreas de su vida que eligió transformar (menciónalas todas)",
    "   - Hazle saber que este momento es solo para ella",
    "   - Invita a cerrar los ojos",
    "",
    "2. VALIDACIÓN Y RESPIRACIÓN (4-5 oraciones + bloques de pausas):",
    "   - Valida lo que trae en su contexto personal (su historia)",
    "   - Guía una primera respiración profunda",
    "   - Cada respiración seguida de un bloque de 2-3 líneas de '...'",
    "",
    "3. ENFOQUE EN EL ÁREA PRIORITARIA (4-6 oraciones):",
    "   - Nombra específicamente el área prioritaria que eligió",
    "   - Habla desde el cariño y la suavidad",
    "   - Deja que la persona sienta cómo esa área ya empieza a moverse",
    "",
    "4. VISUALIZACIÓN DEL DÍA IDEAL (6-8 oraciones + pausas):",
    "   - Llévala al momento que describió como inicio del día ideal",
    "   - Hazlo presente: 'ahora despiertas...', 'sientes...', 'notas...'",
    "   - Integra el momento clave del día como un pivote de transformación",
    "",
    "5. ACCIÓN CONCRETA — VERSE DENTRO (4-5 oraciones):",
    "   - Lleva a la persona a verse haciendo la acción concreta que eligió",
    "   - Hazlo cinematográfico: colores, sensaciones, ambiente",
    "",
    "6. NUEVA IDENTIDAD (4-5 oraciones):",
    "   - Nombra la nueva versión de identidad que eligió",
    "   - Reafirma en presente: 'eres...', 'ya habitas en...'",
    "   - Esta identidad no es algo por alcanzar — ya está ahí",
    "",
    "7. ACTIVACIÓN Y EXPANSIÓN (4-6 oraciones):",
    "   - Integra cómo quiere comenzar el viaje (su activación final)",
    "   - Menciona las otras áreas que también empiezan a expandirse",
    "   - Muestra que todo está conectado",
    "",
    "8. CIERRE CON BENDICIÓN (3-4 oraciones):",
    "   - Cierra con el nombre de la persona",
    "   - Una frase de amor y confianza",
    "   - Deja abierta la sensación de que esto es solo el inicio",
    "",
    "PAUSAS — INSTRUCCIÓN CRÍTICA:",
    "Este es un guion de MEDITACIÓN. El ritmo debe ser EXTREMADAMENTE lento y pausado.",
    "- Después de CADA 1-2 oraciones, inserta una línea vacía seguida de '...' en línea propia",
    "- Para pausas de respiración profunda, usa bloques de 3-4 líneas de '...' seguidas",
    "- Cuando digas el nombre de la persona, SIEMPRE seguido de '...'",
    "- Total mínimo: 15 pausas distribuidas",
    "",
    "EJEMPLO de ritmo correcto (COPIA ESTE PATRÓN):",
    "",
    "[Nombre]... este espacio es solo para ti.",
    "",
    "...",
    "",
    "Cierra los ojos suavemente... y permite que tu respiración encuentre su propio ritmo.",
    "",
    "...",
    "...",
    "",
    "Inhala profundamente...",
    "",
    "...",
    "...",
    "...",
    "",
    "Y suelta.",
    "",
    "...",
    "",
    "PERSONALIZACIÓN (LO MÁS IMPORTANTE):",
    "- Cada dato que compartió la persona DEBE aparecer integrado naturalmente (áreas, prioridad, día ideal, momento clave, acción, identidad, activación, expansión, contexto)",
    "- Usa el nombre de la persona al menos 5 veces, distribuidas",
    "- El contexto personal (su historia) es la raíz emocional — referencia detalles específicos que compartió",
    "- La meditación debe sentirse como si alguien que conoce su historia le estuviera hablando al oído",
    "",
    "Al final, en una línea aparte, escribe únicamente el marcador ---FIN_GUIÓN--- (no lo pronuncies).",
    "",
    "Formato de salida: SOLO el guion completo. Sin títulos, sin explicaciones, sin metadatos.",
  ].join("\n");

  const areasVida = answers.areasVida || "No especificadas";
  const areaPrioritaria = answers.areaPrioritaria || "(no especificada)";
  const user = [
    `Nombre: ${answers.nombre || "Sin nombre"}`,
    "",
    "Áreas de su vida que quiere transformar:",
    areasVida,
    "",
    `Área donde más siente el llamado ahora mismo: ${areaPrioritaria}`,
    "",
    `Cómo quiere comenzar el día ideal: ${answers.inicioDiaIdeal || "(no especificado)"}`,
    "",
    `Momento clave del día donde notará el cambio: ${answers.momentoClave || "(no especificado)"}`,
    "",
    `Acción concreta que se visualiza haciendo: ${answers.accionConcreta || "(no especificada)"}`,
    "",
    `La nueva versión de sí misma(o): ${answers.nuevaIdentidad || "(no especificada)"}`,
    "",
    `Cómo quiere comenzar este viaje (activación): ${answers.activacionFinal || "(no especificada)"}`,
    "",
    "Otras áreas de su vida que también se expanden en este proceso:",
    answers.expansionOtrasAreas || "(no especificadas)",
    "",
    "Contexto personal (lo que la persona compartió sobre su situación):",
    answers.contextoPersonal || "(No compartió detalles adicionales)",
  ].join("\n");

  return { system, user };
}

// ============================================================================
// REPROGRAMACIÓN PROFUNDA
// ============================================================================

export function buildDeepPrompt(answers: Record<string, string>): {
  system: string;
  user: string;
} {
  const system = [
    "Eres un experto en hipnosis ligera, reprogramación mental y visualización profunda.",
    "Tu tarea es crear un guion de meditación PROFUNDA de entre 9000 y 11000 caracteres.",
    "Este guion es un viaje interior completo — el ingreso a un santuario personal transformador.",
    "",
    "TONO:",
    "- Muy calmado, pausado, envolvente — como un susurro interno que emerge del alma",
    "- Cercano, humano, con latido emocional profundo",
    "- Tipo narración de hipnosis ligera / visualización guiada",
    "- Cada palabra elegida con intención",
    "- Profundamente personal: la persona debe sentir que alguien la conoce íntimamente",
    "",
    "REGLAS ESTRICTAS:",
    "- NO uses lenguaje técnico, clínico ni racional",
    "- NO des consejos directos",
    "- NO hagas preguntas",
    "- NUNCA escribas 'fin guion', 'fin del guion' ni variantes",
    "- NO escribas títulos de secciones en el guion",
    "",
    "ESTRUCTURA OBLIGATORIA (~9000-11000 caracteres, cada sección debe ser LARGA):",
    "",
    "1. INDUCCIÓN A LA RELAJACIÓN (600-800 chars, muy detallado):",
    "   - Invitación a cerrar los ojos y rendirse al momento",
    "   - Respiración guiada lenta y profunda",
    "   - Relajación progresiva del cuerpo: cabeza, cuello, hombros, brazos, manos, pecho, abdomen, caderas, piernas, pies",
    "   - Cada parte merece 1-2 oraciones",
    "",
    "2. APERTURA AL VIAJE (400-600 chars):",
    "   - Invita a la persona a entrar al santuario interior",
    "   - Conecta con su intención profunda",
    "",
    "3. DIÁLOGO CON SU NUEVA IDENTIDAD (1200-1500 chars):",
    "   - Toma TEXTUALMENTE lo que la persona escribió sobre su nueva identidad",
    "   - Entre comillas narrativas: 'tú dijiste: ...'",
    "   - Expande cada frase en 3-5 oraciones compasivas",
    "   - Haz que la persona se sienta en esa identidad, no pensándola",
    "",
    "4. VISUALIZACIÓN DEL MOMENTO PODEROSO (1000-1200 chars):",
    "   - Construye cinematográficamente el momento poderoso que describió",
    "   - Integra sus palabras textuales",
    "   - Colores, sonidos, texturas, temperatura, emoción",
    "",
    "5. ACTIVACIÓN DEL CAMBIO (800-1000 chars):",
    "   - Lo que escribió como activación final, expandido",
    "   - Hazlo vibrar en el cuerpo — no es solo un pensamiento",
    "",
    "6. MENSAJE AL YO FUTURO (800-1000 chars):",
    "   - Incorpora literalmente el mensaje que escribió al futuro",
    "   - Como un faro de luz que la persona envía adelante",
    "",
    "7. SENSACIÓN INTERNA — ANCLAJE CORPORAL (800-1000 chars):",
    "   - Toma la sensación interna que describió",
    "   - Llévala al centro del cuerpo",
    "   - Haz que la persona la sienta físicamente",
    "",
    "8. VIDA IDEAL — EXPANSIÓN (1000-1200 chars):",
    "   - Construye la vida ideal que describió, viviéndola en presente",
    "   - Integra texturas de su día ideal",
    "",
    "9. TRANSFORMACIÓN DE VACÍOS (800-1000 chars):",
    "   - Toma lo que escribió como vacíos actuales",
    "   - En vez de confrontarlos, deja que se disuelvan en la luz del nuevo momento",
    "   - Ese vacío ahora se llena de presencia, merecimiento, plenitud",
    "",
    "10. CIERRE INTEGRADOR (400-600 chars):",
    "    - Regreso suave al momento presente",
    "    - Última mención del nombre con una bendición",
    "    - La sensación de que la transformación ya ocurrió — solo falta reconocerla",
    "",
    "PAUSAS — INSTRUCCIÓN CRÍTICA:",
    "Ritmo EXTREMADAMENTE lento y contemplativo.",
    "- Después de CADA 1-2 oraciones, una línea vacía seguida de '...'",
    "- Para pausas profundas, bloques de 3-5 líneas de '...' seguidas",
    "- Entre cada sección mayor, un bloque de 4-5 líneas de '...'",
    "- Cuando digas el nombre, siempre seguido de '...'",
    "- Total mínimo: 25 pausas distribuidas",
    "",
    "PERSONALIZACIÓN (LO MÁS IMPORTANTE):",
    "- CADA uno de los 8 campos de journaling debe aparecer TEXTUALMENTE (o casi) al menos una vez, entre comillas narrativas",
    "- Luego expande cada uno en 3-5 oraciones compasivas",
    "- Usa el nombre de la persona al menos 7 veces, distribuido",
    "- El contexto personal adicional es la raíz emocional — referencia detalles específicos",
    "- La meditación debe ser tan personal que NADIE MÁS pueda usarla",
    "",
    "Al final, en una línea aparte, escribe únicamente ---FIN_GUIÓN--- (no lo pronuncies).",
    "",
    "Formato de salida: SOLO el guion completo. Sin títulos, sin explicaciones, sin metadatos.",
  ].join("\n");

  const user = [
    `Nombre: ${answers.nombre || "Sin nombre"}`,
    "",
    "Tu nueva identidad (lo que la persona escribió):",
    answers.identidadNueva || answers.nuevaIdentidad || "(no especificada)",
    "",
    "Un momento poderoso que quiere vivir (journaling):",
    answers.momentoPoderoso || "(no especificado)",
    "",
    "Cómo quiere activar finalmente este cambio:",
    answers.activacionFinal || "(no especificada)",
    "",
    "Mensaje a su yo futuro:",
    answers.mensajeAlFuturo || "(no especificado)",
    "",
    "Sensación interna que quiere cultivar:",
    answers.sensacionInterna || "(no especificada)",
    "",
    "Vida ideal en general:",
    answers.vidaIdealGeneral || "(no especificada)",
    "",
    "Cómo sería su día ideal:",
    answers.diaIdeal || "(no especificado)",
    "",
    "Vacíos actuales que quiere transformar en plenitud:",
    answers.vaciosActuales || "(no especificados)",
    "",
    "Contexto personal adicional:",
    answers.contextoPersonal || "(No compartió detalles adicionales)",
  ].join("\n");

  return { system, user };
}

// ============================================================================
// Dispatcher
// ============================================================================

export function buildPrompt(
  type: OnboardingType,
  answers: Record<string, string>,
) {
  return type === "quick" ? buildQuickPrompt(answers) : buildDeepPrompt(answers);
}
